Update requirements.txt
Bump Scrapy to 2.6.3, which resolves the `AttributeError: module 'OpenSSL.SSL' has no attribute 'SSLv3_METHOD'` error that resulted from a recent update to the PyOpenSSL package.